CREATE DATABASE PROJETO_VISIO

USE PROJETO_VISIO

CREATE TABLE FUNCIONARIO(

COD_FUNC INT PRIMARY KEY IDENTITY,
NOME_FUNC VARCHAR(50),
TEL_FUNC INT,
EMAIL_FUNC VARCHAR(75)
)

CREATE TABLE CLIENTE(

COD_CLI INT PRIMARY KEY IDENTITY,
NOME_CLI VARCHAR(80),
TEL_CLI INT,
EMAIL_CLI VARCHAR(60)
)

CREATE TABLE PRODUTO(

COD_PROD INT PRIMARY KEY IDENTITY,
NOME_PROD VARCHAR(50),
QUANT_PROD INT,
VALOR_PROD FLOAT

) CREATE TABLE PEDIDO(
FK_COD_PROD INT,
FK_COD_CLI INT,
FOREIGN KEY(C0D_PROD) REFERENCES PRODUTO(COD_PROD),
FOREIGN KEY(C0D_CLI) REFERENCES PRODUTO(COD_CLI),

)CREATE TABLE VENDA(

COD_VEN INT PRIMARY KEY IDENTITY,
DESC_VEN VARCHAR(100),
COD_PED INT,
FORMA_VEN VARCHAR(20),
VALOR_VEN FLOAT,
FK_COD_PED INT,
FOREIGN KEY(FK_COD_PED) REFERENCES PEDIDO(COD_PED)


)
SELECT * FROM FUNCIONARIO
SELECT * FROM CLIENTE
SELECT * FROM PRODUTO
SELECT * FROM PEDIDO
SELECT * FROM VENDA
